version: '3'
services:
  mongodb:
    image: mongo:latest
    ports: 
      - :27018:27017
    volumes:
      - database:/var/lib/db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend_template
    ports: 
      - 3000:3000
    volumes:
      - app:/var/lib/app/frontend_template
  rest_api:
    build:
      context: ../rest_api
      dockerfile: Dockerfile
    image: rest_api
    ports: 
      - 8000:8000
    volumes:
      - app:/var/lib/app/rest_api
    environment:
      - PORT=8000
      - MONGO_DB_URI=mongodb://mongodb:27017/db_container
    depends_on:
      - mongodb
volumes:
  database:
  app: